# Generated by Django 3.1.7 on 2021-03-01 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0002_student_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Dist',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
